services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: memorly-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: memorly
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/memorly --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - memorly-network

  # Extract Features Service
  extract-features-service:
    build: ./services/extract-features-service
    container_name: extract-features-service
    ports:
      - "8001:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8000
    volumes:
      - ./services/extract-features-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Face Extraction Service
  face-extraction-service:
    build: ./services/extract-faces-service
    container_name: face-extraction-service
    ports:
      - "8002:8000"
    environment:
      - B2_KEY_ID=${B2_KEY_ID}
      - B2_APP_KEY=${B2_APP_KEY}
      - B2_BUCKET=${B2_BUCKET}
      - B2_REGION=${B2_REGION}
      - B2_ENDPOINT=${B2_ENDPOINT}
    volumes:
      - ./services/extract-faces-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Embed Service
  embed-service:
    build: ./services/embed-service
    container_name: embed-service
    ports:
      - "8003:8000"
    environment:
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
      - OPENAI_API_KEY=${DEEPINFRA_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - PORT=8000
    volumes:
      - ./services/embed-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Upsert Service
  upsert-service:
    build: ./services/upsert-service
    container_name: upsert-service
    ports:
      - "8004:8000"
    environment:
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
    volumes:
      - ./services/upsert-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Video Segmentation Service
  video-segmentation-service:
    build: ./services/segment-video-service
    container_name: video-segmentation-service
    ports:
      - "8005:8000"
    environment:
      - WHISPER_API_KEY=${DEEPINFRA_API_KEY}
      - WHISPER_BASE_URL=${OPENAI_BASE_URL}
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
      - OPENAI_API_KEY=${DEEPINFRA_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - PORT=8000
    volumes:
      - ./services/segment-video-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Query Processing Service
  query-processing-service:
    build: ./services/query-processing-service
    container_name: query-processing-service
    ports:
      - "8006:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PORT=8000
    volumes:
      - ./services/query-processing-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Search Service
  search-service:
    build: ./services/search-service
    container_name: search-service
    ports:
      - "8007:8000"
    environment:
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
      - MILVUS_TOKEN=${MILVUS_TOKEN}
      - QUERY_PROCESSING_SERVICE_URL=http://query-processing-service:8000
      - EMBED_SERVICE_URL=http://embed-service:8000
      - PORT=8000
    volumes:
      - ./services/search-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - query-processing-service
      - embed-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

  # Gateway Service
  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "9000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - EXTRACT_FEATURES_SERVICE_URL=http://extract-features-service:8000
      - FACE_EXTRACTION_SERVICE_URL=http://face-extraction-service:8000
      - EMBED_SERVICE_URL=http://embed-service:8000
      - UPSERT_SERVICE_URL=http://upsert-service:8000
      - VIDEO_SEGMENTATION_SERVICE_URL=http://video-segmentation-service:8000
      - QUERY_PROCESSING_SERVICE_URL=http://query-processing-service:8000
      - SEARCH_SERVICE_URL=http://search-service:8000
      - FACE_SIMILARITY_THRESHOLD=${FACE_SIMILARITY_THRESHOLD}
      - VIDEO_VISUAL_WEIGHT=${VIDEO_VISUAL_WEIGHT}
      - VIDEO_TEXT_WEIGHT=${VIDEO_TEXT_WEIGHT}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./services/gateway-service:/app
      - gateway-uploads:/tmp/gateway-uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
      - extract-features-service
      - face-extraction-service
      - embed-service
      - upsert-service
      - video-segmentation-service
      - query-processing-service
      - search-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memorly-network

networks:
  memorly-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  gateway-uploads:
    driver: local
